const store = {
  dependencies: [
    { name: "Ace", version: "1.3.0", home: "https://github.com/ajaxorg/ace-builds", },
    { name: "animate.css", version: "4.1.1", home: "", },
    { name: "animejs", version: "3.2.1", home: "", },
    { name: "audiojs", version: "0.1.0", home: "", },
    { name: "Axios", version: "0.27.2", home: "", },
    { name: "Bootstrap", version: "3", home: "", },
    { name: "Bootstrap", version: "4", home: "", },
    { name: "Bootstrap", version: "5", home: "", },
    { name: "clipboard", version: "2.0.11", home: "", },
    { name: "CryptoJS", version: "4.1.1", home: "", },
    { name: "D3", version: "7.4.4", home: "", },
    { name: "director", version: "1.2.8", home: "", },
    { name: "downloadjs", version: "1.4.7", home: "", },
    { name: "Echarts", version: "5.3.3", home: "", },
    { name: "echo-js", version: "1.7.3", home: "", },
    { name: "flowchart", version: "1.2.0", home: "", },
    { name: "gmaps", version: "0.4.25", home: "", },
    { name: "handlebars", version: "4.7.7", home: "", },
    { name: "handsontable", version: "12.0.1", home: "", },
    { name: "hls.js", version: "1.1.5", home: "", },
    { name: "holderjs", version: "2.9.9", home: "", },
    { name: "ionicons", version: "6.0.2", home: "", },
    { name: "jQuery", version: "3.6.0", home: "", },
    { name: "jqvmap", version: "1.5.1", home: "", },
    { name: "js-cookie", version: "3.0.1", home: "", },
    { name: "jsoneditor", version: "9.9.0", home: "", },
    { name: "leaflet", version: "1.8.0", home: "", },
    { name: "markdown-it", version: "13.0.1", home: "", },
    { name: "masonry", version: "0.0.2", home: "", },
    { name: "mathjax", version: "3.2.2", home: "", },
    { name: "mockjs", version: "1.1.0", home: "", },
    { name: "moment", version: "2.29.3", home: "", },
    { name: "monaco-editor", version: "0.33.0", home: "", },
    { name: "mxgraph", version: "4.2.2", home: "", },
    { name: "openlayers", version: "4.6.5", home: "", },
    { name: "randomcolor", version: "0.6.2", home: "", },
    { name: "react", version: "18.2.0", home: "", },
    { name: "require-css", version: "0.1.10", home: "", },
    { name: "requirejs", version: "2.3.6", home: "", },
    { name: "requirejs-plugins", version: "1.0.2", home: "", },
    { name: "requirejs-text", version: "2.0.16", home: "", },
    { name: "slicknav", version: "1.0.8", home: "", },
    { name: "three", version: "0.141.0", home: "", },
    { name: "vibrant", version: "0.0.1", home: "", },
    { name: "video.js", version: "7.19.2", home: "", },
    { name: "vue", version: "3.2.37", home: "", },
    { name: "xlsx", version: "0.18.5", home: "", },
  ]

}